language: node_js
node_js:
- 5.5.0
- '0.12'
script:
- npm test
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- "[[ ! $(node -v) =~ v0.12 ]] && git push origin :gh-pages && git subtree push --prefix
  docs/ origin gh-pages"
notifications:
  slack:
    rooms:
      secure: JSRjS6hsED/W8kpH5/qpO+x5sTpTcpMUjhf/BFp7qV1siqtvn/CRtrOspRTag/ROazhQ/YOrYuXcbNgSv/ABI9xCtPNJQgA+HRLbb6Tq/M+PyDzI+bvQ14MfQ1W3oc457bmxfI03Tol/dObUgTzV0P3bmK6PrefIn/T2FRNv9K+SfJQHoJAzL7QXgZP0C20jxT5WUAeJDYTTp5bWUbhSSjvofxAOa9uMeDyNDIpvqVylw7DGFUW7CmNGP5YCM+55esdzXEL/iaWwVG+ekIPDHN9n42bAFFrHgoVBbjUdCVh3iz6zPrLXZ1mSZglO46ym6gTRt9bbBUwKtprlff9XoqnBlLaeH5Q37vVR1VX9dfQ67wf9cAKtLki/KlxMa6pHEq/v2A6N2m08hMFkc0Dgy1GdyMRKBuV5u7Ir4LIEfZqqh9miPiufW43UhJqlcCnOcdIGkCpOtBB14klPSVcX96VLFEzP7GrXcOT0d1kgQapgXe/bxiE41L3ipLFWsqg4N73vFiiBaGwhihL0OIA4iYMI7+tvaRpp777kynEJb1VMuxGeQeUDteZOZbjcMJUlN+2Cf/E1txJExrWzQfEtpFJnIfTgqXmc0bxgToVLF/9qIWsqKYfZPvMI/xRVuyYYw7SWRE9NxocAqDThMtnbDD+NK93VGdVPGavpdTvMuj4=
env:
  global:
    secure: F0WlcdSCixJLtM6wt3fTsnWPLMcwUiQ/Egi9cu4OZCnVPlZvschOAts9rJYcv3Snt3dwA8wSVmuvH8XsOUs6TCW4JQEvs9anPNp4eTma5XtgAWUHMuGbsOSaZ4oIk8oNSM0QKKHa+bvx2OVSASkg4nqj7g9SGNoxQboHtaF3GFCtGCayhtwhrT+Ik+krcObPdmF5BWaZEl0WAmzWsrpdZN/07sumNwFM032OThiWtju0++EqjZc2bXzGr7PNE3jbpXYQoXjzD3QNPYeJLR904CDSS+wdCLcKZsbQrpx7SPYOiKG8/nSmolWW971U+hz1VdmgjF5SBGyMTKCTDhoy8++iwwyieifmaELZaFa+munqHN3Xd6TE9Jae7cLZINWo6RfxjMxWDZUAd5BLf2UtEUH/e0odL2RNM9t/SJ/4Ev4OxpkVtvZWxg7AP5shSol6RcSPcDd6iWSJpKFKzM4FxZqwKBb9KwmYfvp3mxaXwgNSMFUm3qnr5HnSB/BpXhI2NFuSTddwuZdpr3Fimt9Uh3flEzyn+pdXoIMFPNie5TWvZxHCqyJSIFhW83At2p4nlI+ixdFM+SqRgYRk9Rh5DFFBfr4Z2D/t27cAXFpIseLgnEH5BpSCqDRXXn9uLeh3Jf8tsS4mDxr6eZ5Q7V+Ut0RtHPNGBSgxukmsJelmukA=
